_meta:
  version: '1.0'
  entity_type: menu_link_content
  uuid: 29351102-ae9e-4507-93c7-b42150cf1abb
  bundle: menu_link_content
  default_langcode: en
default:
  enabled:
    -
      value: true
  title:
    -
      value: Products
  menu_name:
    -
      value: main
  link:
    -
      uri: 'internal:/products'
      title: ''
      options: {  }
  external:
    -
      value: false
  rediscover:
    -
      value: true
  weight:
    -
      value: 0
  expanded:
    -
      value: false
  revision_translation_affected:
    -
      value: true
